services:
  web-app:
    build:
      context: .
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env


  db:
    image: postgres:14.6-alpine
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust


  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - web-app
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/default.conf
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/


volumes:
  static_volume:
  media_volume:
  postgresql_data:






